DROP TABLE IF EXISTS reservations;
CREATE TABLE reservations(
id IDENTITY  NOT NULL AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(255)NOT NULL,
time TIMESTAMP  DEFAULT CURRENT_TIMESTAMP()
);

INSERT INTO reservations VALUES(NULL, 'EDGAR', NULL);
INSERT INTO reservations VALUES(NULL, 'SOMEONE ELSE', NULL);

SELECT * FROM reservations